### ISSUE TITLE
Doesn't work with Python 2.7

### ISSUE THREAD

**Issue by mitchelljkotler** [edustaff/django-unused#4]
Tox config suggests that it would, but the code is not compatible with python 2

**Comment by ticalcster** [comment]
What version of Django are you using? Do you have a traceback?

**Comment by mitchelljkotler** [comment]
Python version 2.7.12

```
$ ./manage.py unused templates
Traceback (most recent call last):
  File "./manage.py", line 9, in <module>
    execute_from_command_line(sys.argv)
  File "/home/vagrant/ve/muckrock/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 363, in execute_from_command_line
    utility.execute()
  File "/home/vagrant/ve/muckrock/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 355, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/vagrant/ve/muckrock/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 205, in fetch_command
    klass = load_command_class(app_name, subcommand)
  File "/home/vagrant/ve/muckrock/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 40, in load_command_class
    module = import_module('%s.management.commands.%s' % (app_name, name))
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/vagrant/ve/muckrock/local/lib/python2.7/site-packages/django_unused/management/commands/unused.py", line 4, in <module>
    from ._templates import find_unused_templates, find_unused_templates_whoosh
  File "/home/vagrant/ve/muckrock/local/lib/python2.7/site-packages/django_unused/management/commands/_templates.py", line 37
    print('  Creating Index', end='')
                                 ^
SyntaxError: invalid syntax
```
If I add `from __future__ import print_function` to _templates.py:

```
Traceback (most recent call last):                                                                                                                                                                                                                                             
  File "./manage.py", line 9, in <module>                                                                                                                                                                                                                                      
    execute_from_command_line(sys.argv)                                                                                                                                                                                                                                        
  File "/home/vagrant/ve/muckrock/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 363, in execute_from_command_line                                                                                                                                
    utility.execute()                                                                                                                                                                                                                                                          
  File "/home/vagrant/ve/muckrock/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 355, in execute                                                                                                                                                  
    self.fetch_command(subcommand).run_from_argv(self.argv)                                                                                                                                                                                                                    
  File "/home/vagrant/ve/muckrock/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 205, in fetch_command                                                                                                                                            
    klass = load_command_class(app_name, subcommand)                                                                                                                                                                                                                           
  File "/home/vagrant/ve/muckrock/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 40, in load_command_class                                                                                                                                        
    module = import_module('%s.management.commands.%s' % (app_name, name))                                                                                                                                                                                                     
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module                                                                                                                                                                                                   
    __import__(name)                                                                                                                                                                                                                                                           
  File "/home/vagrant/ve/muckrock/local/lib/python2.7/site-packages/django_unused/management/commands/unused.py", line 4, in <module>                                                                                                                                          
    from ._templates import find_unused_templates, find_unused_templates_whoosh                                                                                                                                                                                                
  File "/home/vagrant/ve/muckrock/local/lib/python2.7/site-packages/django_unused/management/commands/_templates.py", line 6, in <module>                                                                                                                                      
    from tempfile import TemporaryDirectory                                                                                                                                                                                                                                    
ImportError: cannot import name TemporaryDirectory 
```

TemporaryDirectory is not in Python 2.7

**Comment by ticalcster** [comment]
@mitchelljkotler new version has been release on pypi.

**Comment by MrCsabaToth** [comment]
I'm using Python 2.7 and Django 1.11. I needed to install `whoosh` and `backports.tempfile` but then the command runs. During `unused template` `six` errors out due to some Unicode problems. Our source is English, but can contain some unicode like copyright sign and similar. But that would be a different ticket than this.

**Comment by AngelOnFira** [comment]
Tests are working with Python 2.7/Django 1.8 through 1.11, so I recommend that this issue be closed.

```
py27-django18: commands succeeded
py27-django19: commands succeeded
py27-django110: commands succeeded
py27-django111: commands succeeded
```
